### ISSUE TITLE
这个库如何使用能否提供下示例？

### ISSUE THREAD

**Issue by xiaolongyuan** [Tongsuo-Project/tongsuo-go-sdk#10]

**Comment by itomsawyer** [comment]
目前只有ntls Conn层的封装， 示例可以看https://github.com/Tongsuo-Project/tongsuo-go-sdk/blob/main/ntls_test.go

后续还需要封装一些wrapper 才适合出tutorial

**Comment by dongbeiouba** [comment]
详见examples目录，https://github.com/Tongsuo-Project/tongsuo-go-sdk/tree/main/examples

**Comment by Laisky** [comment]
@itomsawyer @dongbeiouba 请问下，如果使用 Go，目前是没法支持基于国密的 TLS1.x ？比如最简单的，开一个单证书的 TLS1.3 connection。
